color0 #171213
color1 #ffb4ab
color2 #ffb0ca
color3 #e2bdc7
color4 #efbc95
color5 #ffb0ca
color6 #e2bdc7
color7 #ebe0e1
color8 #9e8c90
color9 #ffb4ab
color10 #ffb0ca
color11 #e2bdc7
color12 #efbc95
color13 #ffb0ca
color14 #e2bdc7
color15 #ebe0e1

cursor                #ebe0e1
cursor_text_color     #171213
background            #171213
foreground            #ebe0e1
selection_foreground  #d5c2c6
selection_background  #514347
active_border_color   #ffb0ca
inactive_border_color #514347
url_color             #ffb0ca

active_tab_foreground   #5d1135
active_tab_background   #ffb0ca
inactive_tab_foreground #d5c2c6
inactive_tab_background #514347
cursor_trail_color      #d5c2c6
