color0 #141316
color1 #ffb4ab
color2 #d7baff
color3 #cec2da
color4 #f2b7c2
color5 #d7baff
color6 #cec2da
color7 #e7e1e6
color8 #958e99
color9 #ffb4ab
color10 #d7baff
color11 #cec2da
color12 #f2b7c2
color13 #d7baff
color14 #cec2da
color15 #e7e1e6

cursor                #e7e1e6
cursor_text_color     #141316
background            #141316
foreground            #e7e1e6
selection_foreground  #ccc4cf
selection_background  #4a454e
active_border_color   #d7baff
inactive_border_color #4a454e
url_color             #d7baff

active_tab_foreground   #3f1b6e
active_tab_background   #d7baff
inactive_tab_foreground #ccc4cf
inactive_tab_background #4a454e
cursor_trail_color      #ccc4cf
